GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/e564c769-b96f-4c7a-a213-83d75c087d8c

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  
}

###
PATCH http://localhost:3000/orders/e564c769-b96f-4c7a-a213-83d75c087d8c
Content-Type: application/json

{
  "amount": 200
}

###
DELETE http://localhost:3000/orders/e564c769-b96f-4c7a-a213-83d75c087d8c